apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-pvc
  namespace: quote-generator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quote-db-pvc
  namespace: quote-generator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi