apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: quote-generator
  annotations:         
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: api-gateway