apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: quote-generator
spec:
  selector:
    app: api-gateway
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  type: LoadBalancer