apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: quote-generator
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30100
  type: LoadBalancer
