apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: quote-generator
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: quote-generator
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
  type: LoadBalancer