apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: quote-generator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: node-exporter
  ports:
    - port: 9100
      targetPort: 9100
      name: metrics