apiVersion: v1
kind: Service
metadata:
  name: quote-service
  namespace: quote-generator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3002"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: quote-service
  ports:
    - port: 3002
      targetPort: 3002
      name: http
    - port: 9464
      targetPort: 9464
      name: metrics
