apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: quote-generator
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
    - name: prometheus
      port: 15692
      targetPort: prometheus
  type: ClusterIP