apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: quote-generator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3003"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: user-service
  ports:
    - port: 3003
      targetPort: 3003
      name: http
    - port: 9464
      targetPort: 9464
      name: metrics
