apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: quote-generator
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:3000']
        metrics_path: '/metrics'

      - job_name: 'auth-service'
        static_configs:
          - targets: ['auth-service:3001']
        metrics_path: '/metrics'

      - job_name: 'quote-service'
        static_configs:
          - targets: ['quote-service:3002']
        metrics_path: '/metrics'

      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:3003']
        metrics_path: '/metrics'