apiVersion: apps/v1
kind: Deployment
metadata:
 name: api-gateway
 namespace: quote-generator
spec:
 replicas: 2
 selector:
   matchLabels:
     app: api-gateway
 template:
   metadata:
     labels:
       app: api-gateway
   spec:
     containers:
       - name: api-gateway
         image: quote-generator-api-gateway
         imagePullPolicy: Never
         ports:
           - containerPort: 3000
         envFrom:
           - configMapRef:
               name: app-config
           - secretRef:
               name: app-secrets
         resources:
           requests:
             cpu: "100m" 
             memory: "128Mi"
           limits:
             cpu: "200m"
             memory: "256Mi"
         livenessProbe:
           httpGet:
             path: /health
             port: 3000
           initialDelaySeconds: 30
           periodSeconds: 10
         readinessProbe:
           httpGet:
             path: /health
             port: 3000 