apiVersion: apps/v1
kind: Deployment
metadata:
 name: auth-service
 namespace: quote-generator
spec:
 replicas: 2
 selector:
   matchLabels:
     app: auth-service
 template:
   metadata:
     labels:
       app: auth-service
   spec:
     containers:
       - name: auth-service
         image: quote-generator-auth-service
         imagePullPolicy: Never
         command: ["/bin/sh", "-c"]
         args:
          - |
              echo "=== Debug Info ==="
              echo "NODE_ENV: $NODE_ENV"
              echo "MONGO_PORT: $MONGO_PORT"
              echo "MONGO_HOST_AUTH: $MONGO_HOST_AUTH"
              echo "MONGO_DATABASE_AUTH: $MONGO_DATABASE_AUTH"
              echo "Current working directory:"
              pwd
              echo "Directory contents:"
              ls -la
              echo "=== Starting Service ==="
              node dist/src/index.js
         ports:
           - containerPort: 3001
         envFrom:
           - configMapRef:
               name: app-config
           - secretRef:
               name: app-secrets
         resources:
           requests:
             cpu: "100m"
             memory: "128Mi"
           limits:
             cpu: "200m"
             memory: "256Mi"
         readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5  
            failureThreshold: 6  
         livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 45 
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3