apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana 
  namespace: quote-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: GF_PATHS_PROVISIONING
              value: "/etc/grafana/provisioning"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards-config
            items:
              - key: services-overview.json
                path: services-overview.json
              - key: quotes-dashboard.json
                path: quotes-dashboard.json
              - key: api-gateway.json
                path: api-gateway.json
              - key: system-metrics.json
                path: system-metrics.json
        - name: grafana-provisioning-datasources
          configMap:
            name: grafana-provisioning
            items:
              - key: prometheus.yaml
                path: prometheus.yaml
        - name: grafana-provisioning-dashboards
          configMap:
            name: grafana-provisioning
            items:
              - key: default.yaml
                path: default.yaml