apiVersion: apps/v1
kind: Deployment
metadata:
 name: grafana 
 namespace: quote-generator
spec:
 replicas: 1
 selector:
   matchLabels:
     app: grafana
 template:
   metadata:
     labels:
       app: grafana
   spec:
     containers:
       - name: grafana
         image: grafana/grafana
         ports:
           - containerPort: 3000
         resources:
           requests:
             cpu: "100m"
             memory: "128Mi"
           limits:
             cpu: "300m"
             memory: "256Mi"
         volumeMounts:
           - name: grafana-storage
             mountPath: /var/lib/grafana
           - name: grafana-config
             mountPath: /etc/grafana
           - name: grafana-dashboards
             mountPath: /etc/grafana/dashboards
     volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: dashboards
          configMap:
            name: grafana-dashboards-config
            items:
              - key: services-overview.json
                path: services-overview.json
              - key: quotes-dashboard.json
                path: quotes-dashboard.json
              - key: api-gateway.json
                path: api-gateway.json