apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: quote-generator
spec:
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: mongodb
        image: quote-generator-auth-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:   
        - name: auth-db-storage
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_ROOT_PASSWORD
      volumes:    
      - name: auth-db-storage
        persistentVolumeClaim:
          claimName: auth-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-db
  namespace: quote-generator
spec:
  selector:
    matchLabels:
      app: quote-db
  template:
    metadata:
      labels:
        app: quote-db
    spec:
      containers:
      - name: mongodb
        image: quote-generator-quote-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: quote-db-storage
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_ROOT_PASSWORD
      volumes:
      - name: quote-db-storage
        persistentVolumeClaim:
          claimName: quote-db-pvc