apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-service
  namespace: quote-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-service
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox
          command: ['sh', '-c']
          args:
            - |
              until nc -z quote-db 27017 && nc -z rabbitmq 5672; do 
                echo "waiting for dependencies"
                sleep 2
              done
      containers:
        - name: quote-service
          image: quote-generator-quote-service
          imagePullPolicy: Never
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "=== Debug Info ==="
              echo "NODE_ENV: $NODE_ENV"
              echo "MONGO_HOST: $MONGO_HOST"
              echo "MONGO_PORT: $MONGO_PORT"
              echo "MONGO_DATABASE: $MONGO_DATABASE"
              echo "=== Starting Service ==="
              npm start
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGO_HOST
              value: "quote-db"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DATABASE
              value: "quotes"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ROOT_PASSWORD
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@rabbitmq:5672"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            timeoutSeconds: 5