apiVersion: apps/v1
kind: Deployment
metadata:
 name: user-service
 namespace: quote-generator
spec:
 replicas: 2
 selector:
   matchLabels:
     app: user-service
 template:
   metadata:
     labels:
       app: user-service 
   spec:
     initContainers:
        - name: wait-for-dependencies
          image: busybox
          command: ['sh', '-c', 'until nc -z user-db 5432 && nc -z rabbitmq 5672; do echo waiting for dependencies; sleep 2; done;']
     containers:
       - name: user-service
         image: quote-generator-user-service
         imagePullPolicy: Never
         ports:
           - containerPort: 3003
         envFrom:
           - configMapRef:
               name: app-config
           - secretRef:
               name: app-secrets
         resources:
           requests:
             cpu: "100m"
             memory: "128Mi"
           limits:
             cpu: "200m"
             memory: "256Mi"
         livenessProbe:
           httpGet:
             path: /health
             port: 3003
           initialDelaySeconds: 90   
           periodSeconds: 30         
           timeoutSeconds: 15        
           failureThreshold: 3
         readinessProbe:
           httpGet:
             path: /health
             port: 3003
           initialDelaySeconds: 60   
           periodSeconds: 20         
           timeoutSeconds: 10        
           failureThreshold: 3