FROM node:20-alpine as builder
WORKDIR /app

# Build shared
COPY shared ./shared
RUN cd shared && npm install && npm run build

# Build frontend
COPY services/frontend/package*.json ./
RUN npm install
COPY services/frontend ./
RUN npm run build

# Serveur de production léger
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
RUN npm install -g serve
EXPOSE 3006
CMD ["serve", "-s", "dist", "-l", "3006"]